### PR TITLE
Upgrade pnet to 0.25.0

### PR DESCRIPTION
**Pull request by zhangxp1998**
`libpnet` recently merged a bug fix https://github.com/libpnet/libpnet/pull/394

### CODE REVIEW

**Comment by hughesac** [comment]
Thanks for the PR.  I'm just waiting for libpnet to fix the bugs that were introduced in the latest release.

**Comment by imsnif** [comment]
Hey @hughesac - I hope you don't mind the ping. Do you think you'd like to go forward with this now that https://github.com/libpnet/libpnet/pull/403 has been merged, or are there more blockers?

**Comment by zhangxp1998** [comment]
> Hey @hughesac - I hope you don't mind the ping. Do you think you'd like to go forward with this now that [libpnet/libpnet#403](https://github.com/libpnet/libpnet/pull/403) has been merged, or are there more blockers?

Yes I would like to go forward! Let me know if there's anything I need to do. Thanks !

**Comment by hughesac** [comment]
@imsnif  I think we still need to get a new release from libpnet that incorporates the commits from the PR.

**Comment by hughesac** [comment]
I'm closing this since libpnet 0.26 has been released which fixes the broken build and tests.

**Pull request closed without merging**
